BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "sukien" (
	"mask"	TEXT NOT NULL UNIQUE,
	"tensk"	TEXT NOT NULL,
	PRIMARY KEY("mask")
);
CREATE TABLE IF NOT EXISTS "dotuoi" (
	"tuoi"	TEXT NOT NULL,
	"sktuongtung"	TEXT NOT NULL,
	PRIMARY KEY("tuoi")
);
CREATE TABLE IF NOT EXISTS "mauda" (
	"mamau"	INTEGER NOT NULL,
	"tenvung"	TEXT NOT NULL,
	PRIMARY KEY("mamau")
);
CREATE TABLE IF NOT EXISTS "skhanhphuc" (
	"id"	INTEGER NOT NULL UNIQUE,
	"mask"	TEXT NOT NULL,
	"thongtin"	TEXT NOT NULL,
	"image"	TEXT NOT NULL,
	"nu"	TEXT,
	"nam"	TEXT,
	"dotuoi"	INTEGER,
	"danam"	TEXT,
	"danu"	TEXT,
	"ngswap"	INTEGER,
	"vtrinam"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "skchiatay" (
	"id"	INTEGER NOT NULL UNIQUE,
	"mask"	TEXT NOT NULL,
	"thongtin"	TEXT NOT NULL,
	"image"	TEXT NOT NULL,
	"nu"	TEXT,
	"nam"	TEXT,
	"dotuoi"	INTEGER,
	"danam"	TEXT,
	"danu"	TEXT,
	"ngswap"	INTEGER,
	"vtrinam"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "skmuasam" (
	"id"	INTEGER NOT NULL UNIQUE,
	"mask"	TEXT NOT NULL,
	"thongtin"	TEXT NOT NULL,
	"image"	TEXT NOT NULL,
	"nu"	TEXT,
	"nam"	TEXT,
	"dotuoi"	INTEGER,
	"danam"	TEXT,
	"danu"	TEXT,
	"ngswap"	INTEGER,
	"vtrinam"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "sknym" (
	"id"	INTEGER NOT NULL UNIQUE,
	"mask"	TEXT NOT NULL,
	"thongtin"	TEXT NOT NULL,
	"image"	TEXT NOT NULL,
	"nu"	TEXT,
	"nam"	TEXT,
	"dotuoi"	INTEGER,
	"danam"	TEXT,
	"danu"	TEXT,
	"ngswap"	INTEGER,
	"vtrinam"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "skkethon" (
	"id"	INTEGER NOT NULL UNIQUE,
	"mask"	TEXT NOT NULL,
	"thongtin"	TEXT NOT NULL,
	"image"	TEXT NOT NULL,
	"nu"	TEXT,
	"nam"	TEXT,
	"dotuoi"	INTEGER,
	"danam"	TEXT,
	"danu"	TEXT,
	"ngswap"	INTEGER,
	"vtrinam"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "sklyhon" (
	"id"	INTEGER NOT NULL UNIQUE,
	"mask"	TEXT NOT NULL,
	"thongtin"	TEXT NOT NULL,
	"image"	TEXT NOT NULL,
	"nu"	TEXT,
	"nam"	TEXT,
	"dotuoi"	INTEGER,
	"danam"	TEXT,
	"danu"	TEXT,
	"ngswap"	INTEGER,
	"vtrinam"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "skconcai" (
	"id"	INTEGER NOT NULL,
	"mask"	TEXT NOT NULL,
	"thongtin"	TEXT NOT NULL,
	"image"	TEXT NOT NULL,
	"nu"	TEXT NOT NULL,
	"nam"	TEXT NOT NULL,
	"dotuoi"	INTEGER NOT NULL,
	"danam"	TEXT NOT NULL,
	"danu"	TEXT NOT NULL,
	"ngswap"	INTEGER,
	"vtrinam"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "sktuoigia" (
	"id"	INTEGER NOT NULL,
	"mask"	TEXT,
	"thongtin"	TEXT,
	"image"	TEXT,
	"nu"	TEXT,
	"nam"	TEXT,
	"dotuoi"	INTEGER,
	"danam"	TEXT,
	"danu"	TEXT,
	"ngswap"	INTEGER,
	"vtrinam"	TEXT,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "20sk" (
	"stt"	INTEGER NOT NULL,
	"sk1"	TEXT,
	"sk2"	TEXT,
	"sk3"	TEXT,
	"sk4"	TEXT,
	"sk5"	TEXT,
	"sk6"	TEXT,
	"sk7"	TEXT,
	PRIMARY KEY("stt")
);
INSERT INTO "sukien" ("mask","tensk") VALUES ('CT','Sự kiện chia tay'),
 ('HP','Sự kiện hạnh phúc'),
 ('KH','Sự kiện kết hôn'),
 ('LH','Sự kiện ly hôn'),
 ('MS','sự kiện mua sắm'),
 ('NYM','Có người mới');
INSERT INTO "dotuoi" ("tuoi","sktuongtung") VALUES ('20-37 tuổi','HP'),
 ('20-25 tuổi','CT'),
 ('25-30 Tuổi','NYM, KH, MS'),
 ('30-35 tuổi','LH, MS'),
 ('50 trở lên','TG');
INSERT INTO "mauda" ("mamau","tenvung") VALUES (1,'Châu Âu'),
 (2,'Châu Á'),
 (3,'Châu Phi'),
 (4,'Ấn độ'),
 (5,'Đặc biệt');
INSERT INTO "skhanhphuc" ("id","mask","thongtin","image","nu","nam","dotuoi","danam","danu","ngswap","vtrinam") VALUES (1,'HP','You will be taken on a trip by your lover, and the two of you will have fun days together.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/hp1.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp1nu.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp1nam.png',27,'2','2',2,'namtruoc'),
 (2,'HP','You will be taken by your partner to meet their family, to ask for permission to marry you.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/hp5.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp5nu.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp5nam.png',36,'1','1',2,'namtruoc'),
 (3,'HP','You will be given gifts by your lover not on the occasion of a holiday at all','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/hp3.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/hp3.jpg','',25,'1','1',1,''),
 (4,'HP','He will give you a Rolls-Royce car as a birthday present.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/awi1674345583%20(1).png','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/awi1674345583%20(1).png',NULL,32,'1','1',1,''),
 (5,'HP','You will receive a surprise gift from your significant other. Your family will have a new baby.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/hp8.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp8nu.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp8nam.png',35,'1','1',2,'namtruoc'),
 (6,'HP','Three years later, you two will be able to buy a villa.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/hp9.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp9nu.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp9nam.png',30,'3','3',2,'namtruoc'),
 (7,'HP','In 3 years, you will become a billionaire.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/hp13.jpg',NULL,'https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/hp13.jpg',39,'1','',1,''),
 (8,'HP','After 1 year of being in a relationship, you will be fattened up by your significant other by 10 kg.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/hp11.jpg','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/hp11.jpg','',30,'','1',1,''),
 (9,'HP','At the age of 30, the husband will take his family on a world tour using his own airplane.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/hp12.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp12nu.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp12nam.png',50,'1','1',2,'namsau'),
 (10,'HP','At 37 years old, the husband and wife both became a nationally famous acting couple.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/hp14.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp14nu.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp14nam.png',42,'1','1',2,'namtruoc'),
 (11,'HP','After discovering her husband''s affair with his ex-girlfriend, the wife went to the ex-girlfriend''s house to confront her and even resorted to cutting her hair and physically assaulting her.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/anh-chup-man-hinh-2021-04-06-luc-71937-sa-16176697300021258296524.png','','',33,'','2',0,''),
 (12,'HP','After getting married, the husband and wife inherited a large amount of assets from the husband''s stepfather.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/hp16.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp16nu.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/hp16nam.png',40,'1','1',2,'namtruoc');
INSERT INTO "skchiatay" ("id","mask","thongtin","image","nu","nam","dotuoi","danam","danu","ngswap","vtrinam") VALUES (1,'CT','You two break up, when he ''helps'' my best friend out of loneliness by regularly ''having fun'' with her.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/4b8e46b44a99edfc6d585c246c6972030d9c9bb5/ct1.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/1nu.png','0',25,'','2',1,''),
 (2,'CT','You and your significant other will break up because one of you deceived the other and had a third-party relationship.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/101.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nu.101.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nam.101.png',30,'1','',2,'namsau'),
 (3,'CT','You and your partner broke up, because you found out your partner is the third gender','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/103.jpg','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/103.jpg','',30,'','1',1,''),
 (4,'CT','The husband demanded a divorce because the wife looked too ugly after removing her makeup.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/114.jpg','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/114.jpg','0',27,'','4',1,''),
 (5,'CT','You and your boyfriend will break up because he has too much money, and you don''t like wealthy men. It just doesn''t feel safe.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/102.jpg','0','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/102.jpg',35,'1','',1,''),
 (6,'CT','The boyfriend came to visit his girlfriend and got bitten by her dog. They broke up because the boyfriend said that her dog didn''t see him as family.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/ct6.jpg','0','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nam6.png',25,'1','',1,''),
 (7,'CT','She thinks this guy always does ''silly'' things to make her laugh. She likes guys with a little crazy sense of humor. But then she finds out he''s really silly — not that','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/115.jpg','','0',25,'','2',1,''),
 (8,'CT','She tells you that their lifestyles don''t get along because she doesn''t want to be Catholic and doesn''t like raising her children that way.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/3-125921317.jpg','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/3-125921317.jpg','0',27,'','2',1,''),
 (9,'CT','He realizes that''s not who he should marry when people fight with him every day.He listens and tries to fix it to improve the relationship but doesn''t lose. That''s beyond his acceptance threshold','https://raw.githubusercontent.com/thuykieu06012002/futurelove/4b8e46b44a99edfc6d585c246c6972030d9c9bb5/ct2.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nu9.png','0',25,'','1',1,''),
 (10,'CT','He broke up with me. The reason is that my hair is thin, and his hair isn''t very thick either. He''s afraid that if we have children, our hair will become even thinner.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/105.jpg','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/105.jpg','0',25,'','4',1,''),
 (11,'CT','He and I broke up because his mother said I''m not tall enough, which would affect the future of their children. I''m 1m60, and he''s 1m58.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/116.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nu116.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nam116.png',30,'4','4',2,'namsau'),
 (12,'CT','The husband broke up with his wife because of a game that won him one billion.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/117.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nu117.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nam117.png',40,'1','1',2,'namsau'),
 (13,'CT','The wife demanded a breakup because the husband did not call her "wife", and she thought he didn''t love her.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/shutterstock_525808639-1.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/shutterstock_525808639-1.jpg','0',40,'','1',1,''),
 (14,'CT','The wife asked for a divorce from her husband because he was too poor. She was taken care of by a wealthy man.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/108.webp','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/108.webp','0',40,'4','',1,''),
 (15,'CT','After 3 years of dating, the husband won the lottery and became a billionaire. He left his wife and went back to his beautiful ex-girlfriend.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/ct11.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/ct11nu.png','0',35,'1','',1,''),
 (18,'CT','The wife demanded a breakup to go back to her ex-boyfriend because he became a billionaire.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/ct12.jpg','','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/ct12.jpg',35,'5','5',1,''),
 (21,'CT','The wife was surprised to discover a provocative photo of her husband with his lover in her husband''s camera.','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/ct13.jpg','0','0',40,NULL,NULL,0,NULL);
INSERT INTO "skmuasam" ("id","mask","thongtin","image","nu","nam","dotuoi","danam","danu","ngswap","vtrinam") VALUES (1,'MS','Because he still loved his ex-girlfriend, the husband gave her all his money, house, and car. After his wife found out, her family became homeless.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/110.jpg','0','0',45,'5','5',0,''),
 (2,'MS','you and your family go bankrupt, you become homeless','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/110.jpg','0','0',35,'5','5',0,''),
 (3,'MS','You will be jailed in jail for drug use','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/111.jpg','0','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/111.jpg',35,'2','2',1,''),
 (4,'MS','You will become the owner of a 5-star hotel chain','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/3.webp','0','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/3.webp',40,'2','1',1,''),
 (5,'MS','One morning, after waking up, the husband was very surprised that he had won the lottery and become wealthy.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/ms2.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/mnu5.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/mnam5.png',50,'1','2',2,'namsau'),
 (6,'MS','At the age of 45, the husband will become wealthy because his wife is the daughter of a billionaire.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/ms4.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/ms4nu.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/ms4nam.png',45,'5','5',2,'namsau'),
 (7,'MS','At the age of 50, you will become the president of the country.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/84153f9127573de58390f45cec550ab0-16777302887711406046058.jpg','0','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/84153f9127573de58390f45cec550ab0-16777302887711406046058.jpg',50,'2','2',1,''),
 (8,'MS','At the age of 35, the husband will be bought a car by his wife''s family.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/ms1.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/ms1nu.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/ms1nam.png',35,'','2',2,'namtruoc'),
 (9,'MS','At the age of 29, your family will have to beg for a living because the husband has sold the house for gambling.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/hinh-anh-an-xin-hai-huoc-vui-ve_095428938.jpg','0','0',29,'5','5',0,''),
 (10,'MS','At the age of 50, your family will have to sell the house to pay for the husband''s medical treatment due to his frequent alcohol consumption.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/3_thuoc_02-1675655570224.jpg','0','0',50,'5','5',0,''),
 (11,'MS','At the age of 45, you have bought a villa and a luxury car.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/220119161835-02-under-40-rolls-royce-owners.jpg','0','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/220119161835-02-under-40-rolls-royce-owners.jpg',45,'1','1',1,''),
 (12,'MS','The house you can afford to buy at 30? It''s an apartment','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/ms3.jpg','0','0',30,'1','1',0,''),
 (13,'MS','The car you can afford to buy at the age of 30? It''s a bicycle that belongs to both of you.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/113.jpg','0','0',30,'5','5',0,''),
 (14,'MS','After one year of dating, the wife was given a million-dollar mansion as a gift from her husband.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/can-biet-thu-view-bien-1649035543212.jpg','0','0',25,'5','5',0,'');
INSERT INTO "sknym" ("id","mask","thongtin","image","nu","nam","dotuoi","danam","danu","ngswap","vtrinam") VALUES (1,'NYM','One week after breaking up, at her wedding, you caught a glimpse of her older sister. And both of you fell in love after that wedding.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/saostar-le6fhlsuzpwzbgwf.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nnu1.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nnam1.png',27,'1','1',2,''),
 (2,'NYM','What will you be like after 3 years of breaking up? Will you have to get back with your ex because you couldn''t pay off all your debts to them?','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/nym4.jpg','0','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/nym4.jpg',27,'5','5',1,''),
 (3,'NYM','You will have a new lover at your ex-girlfriend''s wedding, and that will be her best friend.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/nym5.jpg','0','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/nym5.jpg',25,'5','5',1,''),
 (4,'NYM','The wife discovered that her husband had proposed to break up with his ex-girlfriend because her family was too poor. He had fallen in love with the wife because of material possessions.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/chia-tay-ban-gai-doi-300-trieu-tien-phi-qua-3-nam-toi-bat-khoc-nhin-nguoi-ben-canh-em-1_248726-1623952986-194-width640height480.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/chia-tay-ban-gai-doi-300-trieu-tien-phi-qua-3-nam-toi-bat-khoc-nhin-nguoi-ben-canh-em-1_248726-1623952986-194-width640height480.jpg','0',30,'','2',1,''),
 (5,'NYM','At the age of 35, the husband and wife will reunite and proceed to marriage.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/nym1.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nym2nu.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nym1nam.png',35,'2','2',2,'namtruoc'),
 (6,'NYM','At the age of 40, the wife returned to her husband because at that time he was a wealthy heir.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/happy-wife-welcoming-her-military-husband-after-returning-back-home-from-army_116547-17523.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/happy-wife-welcoming-her-military-husband-after-returning-back-home-from-army_116547-17523.jpg','0',40,'','3',1,''),
 (7,'NYM','After the breakup, the husband returned to his ex-girlfriend because she was more beautiful than his wife.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/nym6.jpg','0','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/nym6.jpg',30,'5','5',1,''),
 (8,'NYM','At 50 years old, how will the two of you be? The husband already has a new girlfriend, who is a famous singer.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/ct11.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/ct11nu.png','0',50,'1','',1,''),
 (9,'NYM','At 30 years old, who will be in your family? The family consists of 7 people: the husband, the wife, and 5 children.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/nym7.jpg','0','0',30,'5','5',0,''),
 (10,'NYM','After the husband and wife broke up, the husband fell in love with his  best friend and they got married. After a year, they broke up because the husband realized he still loved his ex-wife.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/nym3.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nym3nu.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nym3nam.png',40,'4','4',2,'namtruoc'),
 (11,'NYM','After breaking up, the husband discovered that he was the third sex. Husband and husband''s best friend fell in love','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/dong-tinh-luyen-ai-do-dau11453804634.jpg','0','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nnam11.png',45,'1','',1,''),
 (12,'NYM','One week after breaking up with his wife, the husband started dating his teacher who is 20 years older than him.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/nym8.jpg','0','0',25,'5','5',0,''),
 (13,'NYM','After 2 weeks of breaking up, the wife was proposed by the husband''s older brother. The wife and the older brother got married and lived together under the same roof.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/nym9.jpeg','0','0',27,'5','5',0,'');
INSERT INTO "skkethon" ("id","mask","thongtin","image","nu","nam","dotuoi","danam","danu","ngswap","vtrinam") VALUES (1,'KH','On a fine day, you get good news. The couple had 1 baby and decided to get married. After 1 year together, you suddenly realize that the child is not yours','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/transracial-adoption-racial-identity-single-parent-LGBT.jpg',NULL,'https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/43.jpg',30,'1',NULL,1,'nam sau'),
 (2,'KH','You and she are prevented by your family from coming together. You are forced to marry someone else. For 6 months of marriage, you could not forget about her and had an affair with her','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/featuredImageId26280.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/45.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/44.jpg',25,'1','1',0,NULL),
 (3,'KH','You two are married, one day you are walking down the street to find out he is a third sex, he has been hiding from you for so long','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/77367839.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/46.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/47.jpg',27,'1','1',2,'nam sau'),
 (4,'KH','What happens to you after marriage? You find out he has been having an affair with your best friend. You''re glad there was a reason to break up, because you''re having an affair too.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/ngoai-tinh.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/48.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/49.jpg',25,'1','1',2,'nam sau'),
 (5,'KH','One year after dating, they decided to get married. However, during their wedding night, the husband suddenly felt a strong, uncomfortable odor around him. When he kept asking, the bride finally shyly admitted that she had an issue with body odor.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/999.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/50.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/51.jpg',33,'1','1',2,'nam sau'),
 (6,'KH','The husband and wife were prevented from being together by their families, and the husband was forced to marry someone else. After 6 months of marriage, the husband realized he still loved his ex-wife and had an affair with her.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/tinh-yeu-bi-ngan-cam-boi-gia-dinh-1.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/52.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/53.jpg',30,'1','1',0,NULL),
 (7,'KH','On the day of the wedding of the two, the husband met his ex-girlfriend again and developed feelings for her. In the first month of their marriage, the husband secretly contacted his ex-girlfriend.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/kh4.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/kh4nu.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/kh4nam.png',26,'1','1',2,'nam truoc'),
 (8,'KH','On the wedding day of the couple, the husband had a traffic accident on the way to pick up his wife, was hospitalized, and the wedding ceremony was postponed.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/GettyImages-1230331949-1000x667.jpg',NULL,'https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/56.jpg',40,'2','2',0,NULL),
 (9,'KH','One month after getting married, the husband hit his wife because she didn''t do housework.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/bao-luc-gia-dinh-hien-nay-1200x800-1633638359165423145265-0-128-670-1200-crop-1633638367567377342296.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/57.jpg',NULL,32,'1','1',0,NULL),
 (10,'KH','One week after getting married, the husband lost his memory, forgot his wife, and asked for a divorce. The husband only remembered his ex-girlfriend.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/718aa9a4aae643b81af7.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/58.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/59.jpg',42,'2','2',2,'nam sau'),
 (11,'KH','The wife secretly had an affair with the neighbor because her husband had erectile dysfunction.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/chong-cuong-an-ai-1131.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/61.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/60.jpg',30,'2','2',0,NULL),
 (12,'KH','After 2 years of marriage, the couple went bankrupt because the husband spent all the money on entertainment and girls.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/depositphotos_53691311-stock-photo-broke-bankrupt-young-couple.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/62.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/63.jpg',31,'1','1',2,'nam sau'),
 (13,'KH','The couple had a child, and the husband brought his wife home to introduce her to the family, but they were rejected because the family only liked the husband''s ex-girlfriend.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/khonghoahop.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/64.jpg',NULL,35,NULL,'2',0,NULL),
 (14,'KH','After one week of marriage, the wife asked for a divorce upon discovering that her husband had a child with his ex-girlfriend.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/its-time-to-divorce.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/65.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/66.jpg',27,'1','1',2,'nam sau'),
 (15,'KH','At 45 years old, the couple''s son will marry the ex-girlfriend of the husband and the three of them will live together under one roof.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/chup-anh-gia-dinh-4-nguoi-6-1.png','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/67.png','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/68.png',43,'2','2',2,'nam sau'),
 (16,'KH','At 46 years old, one year after their son married his ex-girlfriend and had a child, the wife discovered that the child was actually her husband''s.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/sinhcongai1-min.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/70.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/69.jpg',23,'2','2',0,'');
INSERT INTO "sklyhon" ("id","mask","thongtin","image","nu","nam","dotuoi","danam","danu","ngswap","vtrinam") VALUES (1,'LH','After 3 years of marriage, the husband and wife divorced because the husband had erectile dysfunction.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/Husband-unhappy-and-disappoint.jpg','0','0',29,'5','5',0,NULL),
 (2,'LH','What happens after you two get married? The two of you will soon break up because your male friend is addicted to alcohol and drugs','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/alcohol-withdrawal-timeline-1.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/72.jpg',NULL,23,NULL,'1',1,NULL),
 (3,'LH','After visiting the hospital for a check-up, the husband discovered that he was infertile, but his wife had a child. So, whose child is it?','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/vo_sinh_nam.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/74.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/73.jpg',34,'1','1',2,'nam truoc'),
 (4,'LH','After 2 years of marriage, the husband and wife have divorced because the wife went to her husband''s company to physically attack him out of jealousy, which impaired his mental well-being.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/couple_argument_yelling.jpg',NULL,'https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/75.jpg',32,'1',NULL,1,'nam sau'),
 (5,'LH','After 2 years of marriage, the husband and wife divorced because the husband discovered that his wife had been having an affair with his brother and that their current child was not his own.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/998.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/76.jpg',NULL,27,NULL,'1',0,NULL),
 (6,'LH','After 1 year of marriage, the wife discovered that her husband was having an affair with her sister behind her back.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/1-1551953708604657186659.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/77.jpg',NULL,35,NULL,'2',0,NULL),
 (7,'LH','After 1 month of marriage, the wife requested a divorce because she found out that her husband was bisexual and had cheated on her with another man.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/2930_1.jpg',NULL,'https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/78.jpg',34,'2',NULL,1,'nam sau'),
 (8,'LH','The husband decided for divorce from his beautiful wife after discovering her deceit. She had never told him about her extensive plastic surgery to look as beautiful as she did.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/upset-chinese-man-woman-having-quarrel-kitchen-middle-aged-young-looking-opposite-sides-husband-wife-thinking-divorce-255720116.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/79.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/80.jpg',30,'2','2',2,'nam sau'),
 (9,'LH','After 1 week of marriage, the wife decided to divorce because she discovered that her husband was not a wealthy heir like she had thought.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/12-Warning-Signs-Your-Marriage-Is-Over-According-To-Experts-6.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/82.jpg',NULL,31,NULL,'1',1,NULL),
 (10,'LH','The husband discovered that his wife had been deceiving him for many years. When they first started dating, she had claimed to be 24 years old, but in reality, she was 34 years old.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/photo1599731820862-15997318208681037861370-crop-1599731880352378356155.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/84.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/83.jpg',33,'2','2',1,'nam truoc'),
 (11,'LH','The husband requested a divorce because his wife was too violent. The wife found out that her husband was having an affair, so she grabbed a knife and hired someone to beat up the other woman.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/ngoai-tinh11-403.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/85.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/86.jpg',29,'2','2',2,'nam sau'),
 (12,'LH','After one month of marriage, the husband requested a divorce because his wife was too dirty. She only took a bath and washed her hair once a week.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/pexels-rhema-11790891-1.jpg',NULL,'https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/87.jpg',33,'3',NULL,1,'nam truoc'),
 (13,'LH','After their wedding night, the husband requested a divorce because he couldn''t accept that his wife was no longer a virgin.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/phu-nu-con-trinh-2.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/88.jpg',NULL,22,NULL,'2',1,NULL),
 (14,'LH','On their wedding night, the wife was extremely upset when she heard her newly-wed husband call her the wrong name, a name of another woman. The next day, she demanded a divorce.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/shutterstock_593479430.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/89.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/90.jpg',34,'1','1',1,NULL),
 (15,'LH','The husband insisted on divorcing because the shaman said that his wife was a "demon" who had bewitched him, always made trouble and took his money.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/women-rights-in-husband-property-after-divorce.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/92.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/91.jpg',25,'1','1',2,'nam truoc'),
 (16,'LH','How will the two of you be at 70 years old? The husband has taken another wife, and there are 3 people living together under the same roof.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/lay-hai-vo.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/93.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/94.jpg',70,'1','1',2,'nam truoc'),
 (17,'LH','How will the two of you be at 70 years old? The husband and wife were abandoned by their children and had to live together in a nursing home ','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/nqh03331-1617362160533182927786.jpg',NULL,'https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/95.jpg',70,'2',NULL,1,'nam truoc'),
 (18,'LH','How will two friends be at 60 years old? At 60 years old, both friends will have passed away.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/vo%20chong.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/98.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/97.jpg',60,'1','1',0,NULL),
 (19,'LH','How will two friends be at 60 years old? At 60 years old, the husband has died because the wife put poison in his food.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/loi-khai-roi-nuoc-mat-cua-nguoi-vo-len-bo-thuoc-doc-vao-thuc-an-cua-chong-suot-2-thang_1.jpg',NULL,'https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/99.jpg',60,'1',NULL,0,NULL),
 (20,'LH','After giving birth, the husband proposed a divorce to his wife because she was too sloppy.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/messy-lady.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/100.jpg',NULL,24,NULL,'2',0,NULL),
 (21,'LH','One week after getting married, the wife demanded a divorce because the husband slapped and hit her for talking too much.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/33227487-husband-wants-to-harm-his-wife-with-slap-domestic-violence.jpg',NULL,NULL,36,'1','1',0,NULL),
 (22,'LH','After 2 months of marriage, the wife requested a divorce because her husband had erectile dysfunction.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/20131126085542-congai1.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/103.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/104.jpg',27,'2',NULL,2,'nam sau'),
 (23,'LH','At the age of 50, the husband requested a divorce after discovering that he had a serious illness.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/co-tich.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/106.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/105.jpg',37,'2','2',1,'nam truoc'),
 (24,'LH','After one year of marriage, the wife gave birth to their first daughter, but the husband demanded a divorce because his family did not like having a granddaughter.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/1_Stressed-Mother-Holding-Crying-Baby-Suffering-From-Post-Natal-Depression-At-Home.png','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/107.png',NULL,33,NULL,'1',1,NULL),
 (25,'LH','After a year of marriage, the wife had an affair with the father-in-law and had a child with him. The husband discovered and requested a divorce. The wife then married the father-in-law, and the husband and wife continued living together and called each other "mother" and "son."','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/photo1595839489548-15958394895591286687615-crop-15958395965421888302794.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/109.jpg','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/108.jpg',49,'4','4',2,'nam truoc'),
 (26,'LH','While shopping, the wife discovered that her husband had lied about going on a business trip. In truth, she caught him cuddling with her best friend.','',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "skconcai" ("id","mask","thongtin","image","nu","nam","dotuoi","danam","danu","ngswap","vtrinam") VALUES (1,'CON','At 36 years old, the husband and wife had to sell their house to hire a lawyer because their son impregnated a 15-year-old girlfriend.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/cc1.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/cc1nu.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/cc1nam.jpg',35,'1','1',2,'nt'),
 (2,'CON','After getting married, the husband and wife had a son. At 20 years old, their son became a successful businessman, while the husband and wife remained penniless.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/cc2.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/cc2nu.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/cc2nam.jpg',50,'4','4',2,'namsau'),
 (3,'CON','After getting married, the husband and wife had a son. The husband and wife had to sell their house because their son was a chip off the old block and liked to party like his father.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/cc3.jpg','0','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/cc3.jpg',35,'2','',1,'0'),
 (4,'CON','After getting married, the husband and wife had a son. The husband and wife were surprised to discover that their son was a third gender person.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/cc4.jpg','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/cc4.jpg','0',40,'','2',1,'0'),
 (5,'CON','After getting married, the husband and wife had a child. During an argument, the child accidentally found out that they were the result of their mother''s affair with an ex-lover.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/cc5.jpg','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/cc5.jpg','0',40,'','1',1,'0'),
 (6,'CON','After getting married, the husband and wife had a child. They were surprised when their son brought home his girlfriend, who turned out to be the husband''s ex-girlfriend.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/cc6.jpg','0','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/cc6.jpg',45,'1','',1,'0'),
 (7,'CON','After their son got married, the wife was surprised to discover that her husband had been having an affair with their daughter-in-law and had a child with her.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/cc7.jpg','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/cc7.jpg','0',40,'','1',1,'0'),
 (8,'CON','After getting married, the husband and wife had a set of twins. When the twins grew up, they unexpectedly developed romantic feelings for each other.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/cc8.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/cc8nu.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/cc8nam.jpg',40,'2','2',2,'namsau');
INSERT INTO "sktuoigia" ("id","mask","thongtin","image","nu","nam","dotuoi","danam","danu","ngswap","vtrinam") VALUES (1,'TG','After getting married, the husband and wife lived happily together until they were 99 years old.','https://raw.githubusercontent.com/ducmanhnguyen1308/-nh-cho-future-love/main/tai-hinh-anh-vo-chong-gia-di-hanh-phuc.jpg','0','0',99,'2','2',0,''),
 (2,'TG','At the age of 60, the husband had an affair with a 35-year-old woman, despite the opposition from his wife and children.','https://raw.githubusercontent.com/thuykieu06012002/futurelove/main/118.jpg','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nu118.png','https://raw.githubusercontent.com/thuykieu06012002/cutimage/main/nam118.png',60,'2','2',2,'namsau'),
 (3,'TG','At 70 years old, the husband and wife became homeless because their daughter-in-law, who is the ex-girlfriend of the husband, kicked them out of the house.','','','',70,'5','5',0,''),
 (4,'TG','At the age of 70, the husband discovered he was infertile and requested a divorce because the wife had four children with someone else.','','','',70,'5','5',0,''),
 (5,'TG','Due to old age and illness, the husband had been bedridden since he turned 60. The wife left him and got together with a wealthy man who was 10 years younger than her.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (6,'TG','After the husband passed away, the wife reunited with her ex-lover after years of being apart. The wife and her ex-lover lived happily together and got married.',NULL,NULL,NULL,55,NULL,NULL,NULL,NULL),
 (7,'TG','The wife discovered that her husband was having an affair with their son''s girlfriend. They had been secretly seeing each other for four months.',NULL,NULL,NULL,70,NULL,NULL,NULL,NULL),
 (8,'TG','The wife discovered that her husband was having an affair with a woman who was 40 years younger than him.',NULL,NULL,NULL,60,NULL,NULL,NULL,NULL),
 (9,'TG','At the age of 55, the husband passed away due to excessive sexual activity that weakened his health.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
 (10,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "20sk" ("stt","sk1","sk2","sk3","sk4","sk5","sk6","sk7") VALUES (1,'','','','','','',''),
 (2,'','','','','','',''),
 (3,'','','','','','',''),
 (4,'','','','','','',''),
 (5,'','','','','','',''),
 (6,'','','','','','',''),
 (7,'','','','','','',''),
 (8,'','','','','','',''),
 (9,'','','','','','',''),
 (10,'','','','','','',''),
 (11,'','','','','','',''),
 (12,'','','','','','',''),
 (13,'','','','','','',''),
 (14,'','','','','','',''),
 (15,'','','','','','',''),
 (16,'','','','','','',''),
 (17,'','','','','','',''),
 (18,'','','','','','',''),
 (19,'','','','','','',''),
 (20,'','','','','','','');
COMMIT;
